import { Inter, Josefin_Slab, Bellota } from "next/font/google";
import "./globals.css";
import store from "./store";
import { Provider } from "react-redux";
import { StoreProvider } from "./store/StoreProvider";

const bellota = Bellota({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-bellota",
});

const josefinSlab = Josefin_Slab({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-josefin-slab",
});

const inter = Inter({
  subsets: ["latin", "cyrillic"],
  weight: ["400", "600", "700"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Wordle",
  description: "Generated by create next app",
  keywords: "Wordle, Game",
  // icon: "./public/Wordle_Logo.png",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </StoreProvider>
  );
}
